deploy1: 
  ReplicaNumber: 1

  containers:
      containerPort: 8080
      image: 'quay.io/roeecr/hello-oc'
      tag: 'chart_v1'

  service:
      servicePort: 8080

deploy2: 
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'quay.io/roeecr/hello-oc'
    tag: 'chart_v1'

  service:
    servicePort: 8080